# Generated by Django 6.0.6 on 2026-06-15 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriaTovara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postavschik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvoditel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PunktVidachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('cena', models.IntegerField()),
                ('skidka', models.IntegerField()),
                ('na_sklade', models.IntegerField()),
                ('opisanie', models.CharField(max_length=400)),
                ('foto', models.FilePathField(default='', path='/home/user/Documents/hexlet/exam/shoes_var/assets')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.kategoriatovara')),
                ('postavschik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.postavschik')),
                ('proizvoditel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.proizvoditel')),
            ],
        ),
    ]
