# Generated by Django 6.0.6 on 2026-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_kategoriatovara_postavschik_proizvoditel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='foto',
            field=models.FilePathField(default='', null=True, path='/home/user/Documents/hexlet/exam/shoes_var/assets'),
        ),
    ]
