# Generated by Django 5.2.11 on 2026-06-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_tovar_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusZakaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('data_zakaza', models.DateField()),
                ('data_dostavki', models.DateField()),
                ('fio_klienta', models.CharField()),
                ('kod', models.IntegerField(unique=True)),
                ('name', models.CharField(unique=True)),
                ('punkt_vidachi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.punktvidachi')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.statuszakaza')),
            ],
        ),
        migrations.CreateModel(
            name='TovarVZakaze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolichestvo', models.IntegerField()),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tovar')),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.zakaz')),
            ],
        ),
    ]
