# Generated by Django 5.2.11 on 2026-06-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_statuszakaza_zakaz_tovarvzakaze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='name',
        ),
    ]
