# Generated by Django 5.2.11 on 2026-06-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_zakaz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='foto',
            field=models.FilePathField(default='picture.png', null=True, path='/home/user/Documents/hexlet/exam/shoes_var/assets'),
        ),
    ]
